import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import RegisterModal from "./components/modals/RegisterModal";
import LoginModal from "./components/modals/LoginModal";
import ToasterProvider from "./components/Providers/ToasterProvider";
import getCurrentUser from "./actions/getCurrenUser";
import RentModal from "./components/modals/RentModal";
import SearchModal from "./components/modals/SearchModal";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "airbnb clone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const currentUser = await getCurrentUser()

  return (
    <html lang="en">
      <body className={font.className}>
          <ToasterProvider />
          <Navbar currentUser={currentUser} />   
          <RegisterModal />
          <RentModal />
          <LoginModal />
          <SearchModal />
          <div className="pb-20 pt-28">
            {children}
          </div>
        </body>
    </html>
  );
}
